project_id = "nmfxfuqolvpikabvqrdk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://nmfxfuqolvpikabvqrdk.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password = true
security_manual_linking_enabled = false

[auth.email]
enabled = true
double_confirm_changes = true
enable_signup = true
secure_password_change = false

[edge_functions]
enabled = true
port = 54329

[functions.send-booking-notification]
verify_jwt = false